default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>


development:
  primary:
    <<: *default
    database: quadrovagas-development
  queue:
    <<: *default
    database: quadrovagas-development-queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: quadrovagas-development-cable
    migrations_paths: db/cable_migrate


test:
  <<: *default
  database: quadrovagas-test
  queue:
    <<: *default
    database: quadrovagas-test-queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: quadrovagas-test-cable
    migrations_paths: db/cable_migrate

production:
  <<: *default
  database: quadrovagas-production